:backup_directory: /home/hex/backup/
:date_format: "%d-%m-%Y"
:zabbix:
  :use: true
  :url: http://domain/api_jsonrpc.php
  :user: Admin
  :password: zabbix
:groups:
  :mikrotik:
    :use: true
    :name: mikrotik
    :user: backup
    :password: backpwd
    :backup_format: :both
    :delete_old: true
    :delete_older_than_days: 14
  :ubiquiti:
    :use: false
  :linux:
    :use: false