# Main backup directory
:backup_directory: /home/hex/backup/
# Date formatting used to create file name
:date_format: "%d-%m-%Y"
# Configuration of Zabbix API connection
:zabbix:
  :enable: true
  :url: http://domain.domain/api_jsonrpc.php
  :user: Admin
  :password: zabbix
# Groups of hosts to backup
:groups:
  :mikrotik:
    :enable: false
    :name: mikrotik
    :user: backup
    :password: backpwd
    # Backup format options:
    # :binary - performs full binary backup (/system backup)
    # :export - exports text configuration (/export)
    # :both - both of them, binary and export together
    :backup_format: :both
    # deletes old files when true
    :delete_old: true
    # delete only files older than value
    :delete_older_than_days: 14
  :ubiquiti:
    :enable: true
    :name: ubiquiti
    :user: ubnt
    :password: ubnt
    # deletes old files when true
    :delete_old: true
    # delete only files older than value
    :delete_older_than_days: 14
  :linux:
    :enable: false